### ISSUE TITLE
Release titles should include version

### ISSUE THREAD

**Issue by w8jcik** [digitaltrails/ddcutil-service#24]
Currently the releases are named in a human readable way

![image](https://github.com/digitaltrails/ddcutil-service/assets/3964620/f4dea1cf-9d0c-4c1c-8555-57cf2a2819b0)

I believe that the more common pattern on GitHub is to put the version in the title.

One could place both version and description if preferred.

**Comment by digitaltrails** [comment]
Thanks for the tip, I will do so in the future.

**Comment by digitaltrails** [comment]
Amended existing releases to include a `v1.0.x - ` prefix.
