### ISSUE TITLE
Dependencies missing from the README.md

### ISSUE THREAD

**Issue by w8jcik** [digitaltrails/ddcutil-service#26]
It is not clear from the instructions what is needed to build this package.

I figured out that this is needed on Ubuntu, but not sure if this is all

```
sudo apt install libglib2.0-dev libddcutil-dev 
```

**Comment by digitaltrails** [comment]
The README.md does include the line:

  > _The service is written in C.  It has very few dependencies (glib and libddcutil) and is
consequently quite easy to build._

Plus the `spec` file is quite explicit about what is required.

But to be clearer, I will list them in a section and correct `glib` to `glib-2`.  I consider it up to the person distributing or building to figure out how that translates to exact distro-specific dependencies.

**Comment by digitaltrails** [comment]
Added more info on dependencies.
